-- ASOC notification/location/status extension for PostgreSQL 14+.
-- Prerequisite: run src/db/schema.sql first so loads(load_id) and
-- drivers(driver_id) exist. This script is idempotent.
BEGIN;

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id TEXT REFERENCES drivers(driver_id) ON DELETE SET NULL,
  load_id TEXT REFERENCES loads(load_id) ON DELETE CASCADE,
  channel TEXT NOT NULL
    CHECK (channel IN ('in_app', 'sms', 'email', 'push', 'webhook')),
  event_type TEXT NOT NULL,
  recipient TEXT,
  subject TEXT,
  body TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'sending', 'sent', 'delivered', 'failed', 'read', 'cancelled')),
  provider_message_id TEXT,
  idempotency_key TEXT UNIQUE,
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  scheduled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  read_at TIMESTAMPTZ,
  failed_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS notifications_dispatch_idx
  ON notifications (scheduled_at, id)
  WHERE status = 'queued';
CREATE INDEX IF NOT EXISTS notifications_driver_idx
  ON notifications (driver_id, created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_load_idx
  ON notifications (load_id, created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_provider_message_idx
  ON notifications (provider_message_id)
  WHERE provider_message_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS driver_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id TEXT NOT NULL REFERENCES drivers(driver_id) ON DELETE CASCADE,
  load_id TEXT REFERENCES loads(load_id) ON DELETE SET NULL,
  latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  accuracy_meters DOUBLE PRECISION CHECK (accuracy_meters IS NULL OR accuracy_meters >= 0),
  speed_mph DOUBLE PRECISION CHECK (speed_mph IS NULL OR speed_mph >= 0),
  heading_degrees DOUBLE PRECISION
    CHECK (heading_degrees IS NULL OR (heading_degrees >= 0 AND heading_degrees < 360)),
  source TEXT NOT NULL DEFAULT 'gps'
    CHECK (source IN ('gps', 'network', 'manual', 'webhook')),
  captured_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS driver_locations_driver_time_idx
  ON driver_locations (driver_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS driver_locations_load_time_idx
  ON driver_locations (load_id, captured_at DESC)
  WHERE load_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS driver_locations_recent_idx
  ON driver_locations (captured_at DESC);

CREATE TABLE IF NOT EXISTS load_status_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  load_id TEXT NOT NULL REFERENCES loads(load_id) ON DELETE CASCADE,
  previous_status TEXT,
  status TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'api',
  actor_type TEXT,
  actor_id TEXT,
  latitude DOUBLE PRECISION CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  longitude DOUBLE PRECISION CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key TEXT UNIQUE,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS load_status_events_load_time_idx
  ON load_status_events (load_id, occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS load_status_events_status_time_idx
  ON load_status_events (status, occurred_at DESC);

COMMIT;
